"""add Service model

Revision ID: 051d254a1f08
Revises: ac49f5ae014a
Create Date: 2025-08-02 19:15:46.480122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051d254a1f08'
down_revision = 'ac49f5ae014a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))
        batch_op.drop_column('description_en')
        batch_op.drop_column('title_ar')
        batch_op.drop_column('title_en')
        batch_op.drop_column('title_it')
        batch_op.drop_column('description_ar')
        batch_op.drop_column('description_it')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_it', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('description_ar', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('title_it', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('title_en', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('title_ar', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.TEXT(), nullable=False))
        batch_op.drop_column('image_filename')
        batch_op.drop_column('category')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
